postgres:
  connection_string: postgresql://focus:Babaganoush1.@localhost:5432/fenologik
  auto_publish: true
  tables:
    observations:
      schema: public
      table: observations
      srid: 4326
      geometry_column: position
      bounds:
      - 11.19531
      - 55.3778
      - 24.14003
      - 67.67649
      geometry_type: POINT
      properties:
        end_date: timestamp
        id: varchar
        organism_quantity: int4
        start_date: timestamp
        taxon_id: int4
    polygon:
      schema: public
      table: polygon
      srid: 4326
      geometry_column: geom
      bounds:
      - 10.5935025
      - 55.1370957
      - 24.1776819
      - 69.0599735
      geometry_type: MULTIPOLYGON
      properties:
        id: int4
        name: varchar
    polygon.1:
      schema: public
      table: polygon
      srid: 3857
      geometry_column: geom_3857
      bounds:
      - 10.5935025
      - 55.13709570000001
      - 24.177681899999996
      - 69.0599735
      geometry_type: MULTIPOLYGON
      properties:
        id: int4
        name: varchar
    square_grid:
      schema: public
      table: square_grid
      srid: 3857
      geometry_column: geom
      bounds:
      - 10.578560785791485
      - 55.05629757726598
      - 24.376683549867334
      - 69.16808747092355
      geometry_type: POLYGON
      properties:
        id: int4
        zoom_level: int4
    square_grid_0:
      schema: public
      table: square_grid_0
      srid: 3857
      geometry_column: geom
      geometry_type: POLYGON
      properties:
        id: int4
    square_grid_1:
      schema: public
      table: square_grid_1
      srid: 3857
      geometry_column: geom
      geometry_type: POLYGON
      properties:
        id: int4
    square_grid_obs_count:
      schema: public
      table: square_grid_obs_count
      srid: 3857
      geometry_column: geom
      bounds:
      - 11.038498211260679
      - 55.31887076144413
      - 24.376683549867334
      - 67.81961120223927
      geometry_type: POLYGON
      properties:
        id: int4
        obs_count: int4
    square_grid_zoom_0:
      schema: public
      table: square_grid_zoom_0
      srid: 3857
      geometry_column: geom
      bounds:
      - 10.578560785791485
      - 55.05629757726598
      - 24.376683549867334
      - 69.16808747092355
      geometry_type: POLYGON
      properties:
        id: int4
    square_grid_zoom_1:
      schema: public
      table: square_grid_zoom_1
      srid: 3857
      geometry_column: geom
      bounds:
      - 10.578560785791485
      - 55.05629757726598
      - 24.376683549867334
      - 69.08615069107711
      geometry_type: POLYGON
      properties:
        id: int4
  functions:
    grid_function:
      schema: public
      function: grid_function
